twilio: # Twilio gateway configuration
  accountId: AC9820e2a0c63ae7e8e7b57181a8b728fc
  accountToken: 6d074cf7775618255b369c6227f97d51
  numbers: # Numbers allocated in Twilio
    - +12037699488 # First number
    #- # Second number
    #- # Third number
    #- # ...
    #- # Nth number
  messagingServicesId: 123
  localDomain: localhost # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: 10 # Size of push pending queue

turn: # TURN server configuration
  secret: unknow2 # TURN server secret
  uris:
    - stun:yourdomain:80
    - stun:yourdomain.com:443
    - turn:yourdomain:443?transport=udp
    - turn:etc.com:80?transport=udp

#redphone:
#  authKey: unknow1 # Deprecated

cache: # Redis server configuration for cache cluster
  url: 'redis://localhost:6379/1'

directory: # Redis server configuration for directory cluster
  url: 'redis://localhost:6379/1'

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://127.0.0.1:5432/messagedb

messageCache: # 自己随便加的
  redis: 
    url: 'redis://localhost:6379/1'
  cacheRate: 1
  persistDelayMinutes: 60

attachments: # AWS S3 configuration
  accessKey: AKIAIPAPLLQMCIL5J7FA
  accessSecret: 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
  bucket: walletsplus

profiles: # AWS S3 configuration
  accessKey: AKIAIPAPLLQMCIL5J7FA
  accessSecret: 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
  bucket: walletsplus
  region: 'Asia Pacific (Tokyo)'

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://127.0.0.1:5432/accountsdb

apn: # Apple Push Notifications configuration
  bundleId: com.bamboo.tokenpipe
  pushCertificate: ../config/aps_development.cer
  pushKey: ../config/push_dev.p12

gcm: # GCM Configuration
  senderId: 12345
  apiKey: apiKey
